spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

s3:
  endpointUrl: http://127.0.0.1:9000
  accessKey: C700CAUK6LF9SW47IHXW
  secretKey: lX4aUzkVC5fynMfM3myPmFA5WcBJ38nhIbpc6ujP
  bucketName: moviefun